
------ APP ----------
CREATE TABLE APP (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(300) NOT NULL 
);

------ FORM ----------
CREATE TABLE FORM (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(300) NOT NULL,
	LABEL VARCHAR(350),
	ID_APP INTEGER NOT NULL	
);
ALTER TABLE FORM
ADD CONSTRAINT FOREIGN KEY(ID_APP)
REFERENCES APP(ID);


---- FIELD ----------
CREATE TABLE FIELD (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(300) NOT NULL,
	ID_FORM INTEGER NOT NULL	
);
ALTER TABLE FIELD
ADD CONSTRAINT FOREIGN KEY(ID_FORM)
REFERENCES FORM(ID);
 
CREATE TABLE FIELD_ATTRIBUTE (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	LABEL VARCHAR(300) NOT NULL,
	FIELD_TYPE INT NOT NULL,
	DATA_TYPE INT NOT NULL,
	FORMAT_TYPE INT, 
	ID_FIELD BIGINT NOT NULL	
);
ALTER TABLE FIELD_ATTRIBUTE
ADD CONSTRAINT FOREIGN KEY(ID_FIELD)
REFERENCES FIELD(ID);


---- FORM_REGISTER ----------
CREATE TABLE FORM_REGISTER (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	ID_FORM INT NOT NULL
)
ALTER TABLE FORM_REGISTER
ADD CONSTRAINT FOREIGN KEY(ID_FORM)
REFERENCES FORM(ID);

CREATE TABLE FIELD_VALUE (
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	VAL VARCHAR(800), 
	ID_REGISTER BIGINT NOT NULL,
	ID_FIELD BIGINT NOT NULL	
)
ALTER TABLE FIELD_VALUE
ADD CONSTRAINT FOREIGN KEY(ID_REGISTER)
REFERENCES FORM_REGISTER(ID);
ALTER TABLE FIELD_VALUE
ADD CONSTRAINT FOREIGN KEY(ID_FIELD)
REFERENCES FIELD(ID);


ALTER TABLE APP 
ADD COLUMN STATUS INT
-- STATUS APP { 1 - HABILITADA, 2 - DESABILITADA }








